name: zart_cli
description: CLI Player For Zart Library.
homepage: https://atebitftw.github.io/site/
repository: https://github.com/atebitftw/zart_cli
issue_tracker: https://github.com/atebitftw/zart_cli/issues
version: 1.0.0
publish_to: none

environment:
  sdk: ^3.10.4
executables:
  zart:
# Add regular dependencies here.
dependencies:
  dart_console:
  logging: 
  # zart: ^1.9.3
  zart:
    path: "e:/dev/projects/zart"
dev_dependencies:
  lints: ^6.0.0
  test: ^1.25.6
